# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20170818_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=256, null=True, verbose_name='Branch name ')),
                ('place_of_position', models.TextField(blank=True, null=True, verbose_name='Place of position')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=256, null=True, verbose_name='Company ')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='images/company', verbose_name='Company image')),
                ('company_status', models.BooleanField(default=False, verbose_name='Company Status')),
            ],
        ),
        migrations.AddField(
            model_name='assignproduct',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assignproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prdduct', to='product.Product', verbose_name='Product'),
        ),
    ]
