# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170818_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignproduct',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='assignproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_product', to='product.Product', verbose_name='Product'),
        ),
    ]
