# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170818_0716'),
        ('company', '0003_auto_20170818_1027'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignproduct',
            unique_together=set([('company', 'product')]),
        ),
    ]
