# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_auto_20170821_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_auto_20170818_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(null=True, verbose_name='Box ID')),
                ('key_status', models.CharField(choices=[('In', 'inside'), ('Out', 'out')], default='In', max_length=255, verbose_name='Key Staus')),
                ('createdat', models.DateTimeField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_name', to='company.AssignProduct', verbose_name='Branch Name')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_name', to='company.Company', verbose_name='Company')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(max_length=256, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.Product', verbose_name='Product ID')),
            ],
        ),
    ]
