# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystatus',
            name='branch',
            field=models.CharField(max_length=255, null=True, verbose_name='Branch name'),
        ),
        migrations.AlterField(
            model_name='keystatus',
            name='company',
            field=models.CharField(max_length=255, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='keystatus',
            name='createdat',
            field=models.CharField(max_length=255, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='keystatus',
            name='createdby',
            field=models.CharField(max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='keystatus',
            name='product_id',
            field=models.IntegerField(max_length=256, null=True, verbose_name='Product ID'),
        ),
    ]
