# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyStatus', '0002_auto_20170926_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keystatus',
            name='product_id',
            field=models.IntegerField(null=True, verbose_name='Product ID'),
        ),
    ]
