# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=256, null=True, verbose_name='Product id')),
                ('boxcount', models.IntegerField(max_length=50, null=True, verbose_name='Box count')),
                ('mfg_date', models.DateField(verbose_name='Manufacturing Date')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/product/')),
                ('product_status', models.BooleanField(default=False, verbose_name='Product Status')),
            ],
        ),
    ]
