# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('SuperAdmin', 'SuperAdmin'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee')], max_length=50, unique=True, verbose_name='User type')),
                ('can_add_admin', models.BooleanField(default=False, verbose_name='Can add admin')),
                ('can_edit_admin', models.BooleanField(default=False, verbose_name='Can edit admin')),
                ('can_delete_admin', models.BooleanField(default=False, verbose_name='Can delete admin')),
                ('can_viewlog_admin', models.BooleanField(default=False, verbose_name='Can view log information admin')),
                ('can_add_manager', models.BooleanField(default=False, verbose_name='Can add manager')),
                ('can_edit_manager', models.BooleanField(default=False, verbose_name='Can edit manager')),
                ('can_delete_manager', models.BooleanField(default=False, verbose_name='Can delete manager')),
                ('can_viewlog_manager', models.BooleanField(default=False, verbose_name='Can view log information manager')),
                ('can_add_employee', models.BooleanField(default=False, verbose_name='Can add manager')),
                ('can_edit_employee', models.BooleanField(default=False, verbose_name='Can edit manager')),
                ('can_delete_employee', models.BooleanField(default=False, verbose_name='Can delete manager')),
                ('can_viewlog_employee', models.BooleanField(default=False, verbose_name='Can view log information employee')),
            ],
        ),
    ]
