# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0002_auto_20170823_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadminusers',
            name='admin_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users', verbose_name='Admin user'),
        ),
    ]
