# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('view_task', 'Can see available tasks'), ('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed'))},
        ),
    ]
